name: Create release tarball from tag

on: 
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.node-version'
    - run: pnpm install --frozen-lockfile
    - run: VERSION=$(scripts/get-version-from-git.sh) pnpm dist
      env:
        RIOT_OG_IMAGE_URL: https://web.synod.im/themes/element/img/logos/synod-im-logo-color.png
        CI_PACKAGE: true
    - uses: softprops/action-gh-release@v2
      with:
        files: dist/*.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v6
      with:
        name: synod-web
        path: webapp

  deploy-to-staging:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/download-artifact@v6
      with:
        name: synod-web
        path: webapp
    - name: Setup ssh keys
      run: |
        mkdir ~/.ssh
        echo '${{ secrets.SSH_PRIVATE_KEY }}' > ~/.ssh/id_rsa
        echo '${{ secrets.SSH_PUBLIC_KEY }}' > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
    - name: Deploy to web.staging.synod.im
      run: rsync -e "ssh -o StrictHostKeyChecking=no" -arvc webapp/ lki01-synodstaging@lki01.hostsharing.net:/home/pacs/lki01/users/synodstaging/doms/staging.synod.im/subs-ssl/web
